# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 752d85e260158448127a0e70035c1f21a9a6255867098612271b845dbe4ab2f1ae92135da3ea5fb8aded5e79032a899e518ad492035bda7953e716334da66ac3

test:
  secret_key_base: 2e24225ae7ebb3155721468dff71f40f1b014d0635fbc3117b7a243277683cee74481d7e8715b2db976a591260c455e291d7c3af7c51200655ec804b6612ee5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
